# Generated by Django 5.0.6 on 2026-09-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0002_nfc_encrypted_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assigned_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_users', to='students.department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='assigned_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_users', to='students.school'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('security_chief', 'Security Chief'), ('security', 'Security Guard'), ('lecturer', 'Lecturer'), ('hod', 'Head of Department'), ('dean', 'Dean'), ('student', 'Student')], default='admin', max_length=20),
        ),
    ]
