# Generated by Django 5.0.6 on 2026-09-05 22:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='students_co_code_c48562_idx'), models.Index(fields=['is_active'], name='students_co_is_acti_d799b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('diploma', 'Diploma'), ('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PhD')], db_index=True, default='bachelor', max_length=20)),
                ('duration_years', models.PositiveIntegerField(default=3)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='students.department')),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='students.college')),
            ],
            options={
                'ordering': ['college', 'name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='students.school'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_registration_number', message='Registration number must contain only uppercase letters and numbers', regex='^[A-Z0-9]+$')])),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('year_of_study', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], db_index=True, default=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.program')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.school')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='NFCCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('lost', 'Lost/Stolen')], db_index=True, default='active', max_length=20)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivation_reason', models.TextField(blank=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_card', to='students.student')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['department', 'is_active'], name='students_pr_departm_e2499c_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['level'], name='students_pr_level_0eb217_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('department', 'code')},
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['college', 'is_active'], name='students_sc_college_854b6f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('college', 'code')},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['school', 'is_active'], name='students_de_school__9c9569_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('school', 'code')},
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['college', 'is_active'], name='students_st_college_14b34a_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department', 'is_active'], name='students_st_departm_cec055_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['year_of_study'], name='students_st_year_of_55109d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active', 'admission_date'], name='students_st_is_acti_c87fac_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['status'], name='students_nf_status_ba8d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['uid'], name='students_nf_uid_f8eba3_idx'),
        ),
    ]
