# Generated by Django 5.0.6 on 2026-09-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfccard',
            name='uid',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
