# Generated by Django 5.0.6 on 2026-09-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_nfc_encrypted_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfccard',
            name='card_serial',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
