# Generated by Django 5.0.6 on 2026-09-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='type',
            field=models.CharField(choices=[('device_mismatch', 'Device Ownership Mismatch'), ('card_sharing', 'Card Sharing Attempt'), ('unauthorized_entry', 'Unauthorized Campus Entry'), ('stolen_device', 'Stolen Device Report'), ('stranger', 'Unregistered Person on Campus'), ('other', 'Other')], max_length=50),
        ),
    ]
