# Generated by Django 5.0.6 on 2026-09-23 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('devices', '0001_initial'),
        ('students', '0003_nfc_card_serial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('owner', 'Registered owner'), ('borrower', 'Authorised borrower'), ('mismatch', 'Mismatch'), ('student_only', 'Student only'), ('device_only', 'Device only')], db_index=True, max_length=20)),
                ('identified_by', models.CharField(blank=True, max_length=20)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_checks', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checks', to='devices.device')),
                ('gate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_checks', to='campus.gate')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_checks', to='students.student')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
