# Generated by Django 5.0.6 on 2026-09-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_class_attendance_tracking'),
        ('students', '0002_nfc_encrypted_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='students.department'),
        ),
    ]
