# Generated by Django 5.0.6 on 2026-09-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_course_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='method',
            field=models.CharField(choices=[('nfc', 'Card'), ('manual', 'Manual Entry')], default='nfc', max_length=20),
        ),
    ]
